# Datawrapper configuration
#

domain: datawrapper
chart_domain: c.datawrapper

# show debug message?
debug: true

# some default values
default_theme: deutsche-welle
default_vis: bar-chart

# thumbnail sizes [width, height]
thumbnails:
    s: [150, 84]
    m: [300, 168]
    l: [400, 225]

# email address for admin
admin_email: milan.burgmann@dw.de
log_email: milan.burgmann@dw.de

# piwik tracking code
piwik:
    url: datastory.de/piwik  # without http:// and trailing slash
    idSite: 5
    # idSiteNoCharts: 6  # additionally, you can track the user interface w/o the charts, too

# optional: publish your charts on Amazon S3

# s3:
#     bucket: BUCKET_NAME
#     accesskey: YOUR_AWS_ACCESS_KEY
#     secretkey: YOUR_AWS_SECTET_KEY